### ISSUE TITLE
Research using a database ORM

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-decoder-service#2]
It would be very useful to find something similar to Django Admin. Some alternatives:

- TortoiseORM and https://fastapi-admin-docs.long2ice.io/
- SqlModel and https://github.com/aminalaee/sqladmin

SqlModel is the one designed by the authors of FastAPI, so I'm a little biased to use that

**Comment by moisses89** [comment]
I was testing both admins, both looks fine, but I will say continue with sqladmin. 
Fastapi-admin looks a discontinued project, their last release is 2 years ago. 
SqlAdmin supports [AQLAlchemy](https://docs.sqlalchemy.org/en/20/orm/) too, that is an extensive ORM. SqlModel is based on it. 
The documentation of SQLAdmin is much better. 

I will go with SQLAdmin @Uxio0 what do you think?

**Comment by Uxio0** [comment]
Thanks for the analysis. `SQLAlchemy` is very well known project, well maintained and I have used it in the past. Also `SqlModel` is from the FastAPI authors. I would go for it too
